# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tron.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'tron.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntron.proto\x12\x04tron\"\x18\n\x07GridRow\x12\r\n\x05\x63\x65lls\x18\x01 \x03(\x08\"4\n\x06Player\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61n_move\x18\x03 \x01(\x08\"G\n\tGameState\x12\x1b\n\x04grid\x18\x01 \x03(\x0b\x32\r.tron.GridRow\x12\x1d\n\x07players\x18\x02 \x03(\x0b\x32\x0c.tron.Player\",\n\x04Game\x12$\n\x0bgame_states\x18\x01 \x03(\x0b\x32\x0f.tron.GameState\"\"\n\x05Games\x12\x19\n\x05games\x18\x01 \x03(\x0b\x32\n.tron.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tron_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRIDROW']._serialized_start=20
  _globals['_GRIDROW']._serialized_end=44
  _globals['_PLAYER']._serialized_start=46
  _globals['_PLAYER']._serialized_end=98
  _globals['_GAMESTATE']._serialized_start=100
  _globals['_GAMESTATE']._serialized_end=171
  _globals['_GAME']._serialized_start=173
  _globals['_GAME']._serialized_end=217
  _globals['_GAMES']._serialized_start=219
  _globals['_GAMES']._serialized_end=253
# @@protoc_insertion_point(module_scope)
