syntax = "proto3";

package tron;

message Player {
  int32 idx = 1;
  bool can_move = 2;
}

message GameState {
  int32 num_rows = 1;
  int32 num_cols = 2;
  bytes board = 3; // Unsigned little-endian integer bytes.
  repeated Player players = 4;
}

message Game {
  repeated GameState game_states = 1;
}

message Games {
  repeated Game games = 1;
}


enum GameResult {
  GAME_RESULT_UNSPECIFIED = 0;
  P1_WIN = 1;
  P2_WIN = 2;
  TIE = 3;
}

message LabeledGameState {
  GameState game_state = 1;
  GameResult result = 2;
  int32 steps_to_result = 3;
}

message LabeledGameStates {
  repeated LabeledGameState labeled_states = 1;
}
