# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tron.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tron.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntron.proto\x12\x04tron\"\'\n\x06Player\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61n_move\x18\x02 \x01(\x08\"]\n\tGameState\x12\x10\n\x08num_rows\x18\x01 \x01(\x05\x12\x10\n\x08num_cols\x18\x02 \x01(\x05\x12\r\n\x05\x62oard\x18\x03 \x01(\x0c\x12\x1d\n\x07players\x18\x04 \x03(\x0b\x32\x0c.tron.Player\",\n\x04Game\x12$\n\x0bgame_states\x18\x01 \x03(\x0b\x32\x0f.tron.GameState\"\"\n\x05Games\x12\x19\n\x05games\x18\x01 \x03(\x0b\x32\n.tron.Game\"r\n\x10LabeledGameState\x12#\n\ngame_state\x18\x01 \x01(\x0b\x32\x0f.tron.GameState\x12 \n\x06result\x18\x02 \x01(\x0e\x32\x10.tron.GameResult\x12\x17\n\x0fsteps_to_result\x18\x03 \x01(\x05\"C\n\x11LabeledGameStates\x12.\n\x0elabeled_states\x18\x01 \x03(\x0b\x32\x16.tron.LabeledGameState*J\n\nGameResult\x12\x1b\n\x17GAME_RESULT_UNSPECIFIED\x10\x00\x12\n\n\x06P1_WIN\x10\x01\x12\n\n\x06P2_WIN\x10\x02\x12\x07\n\x03TIE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tron_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMERESULT']._serialized_start=423
  _globals['_GAMERESULT']._serialized_end=497
  _globals['_PLAYER']._serialized_start=20
  _globals['_PLAYER']._serialized_end=59
  _globals['_GAMESTATE']._serialized_start=61
  _globals['_GAMESTATE']._serialized_end=154
  _globals['_GAME']._serialized_start=156
  _globals['_GAME']._serialized_end=200
  _globals['_GAMES']._serialized_start=202
  _globals['_GAMES']._serialized_end=236
  _globals['_LABELEDGAMESTATE']._serialized_start=238
  _globals['_LABELEDGAMESTATE']._serialized_end=352
  _globals['_LABELEDGAMESTATES']._serialized_start=354
  _globals['_LABELEDGAMESTATES']._serialized_end=421
# @@protoc_insertion_point(module_scope)
